### PR TITLE
start conversion to python 3

### PR DESCRIPTION
**Pull request by tomshaffner**

### CODE REVIEW

**Comment by rudolf-bauer** [comment]
Hi @marians, I would like to build a Python3-based genesis library with `pandas` support an focus on `destatis.de`. However, I am not interested in supporting a cli or the full genesis API for all sites. 

If you are interested, I can contribute all my code into your repository. However, I am a bit unsure, since the project seems to be quite inactive and the maintainance processes seem to be slow. Please tell me, if you are interested in an active development. Otherwise, I will work on a separate project/repository.

**Comment by marians** [comment]
Thanks for reaching out! However I am currently not able to actively develop this repository.

Feel free to send a PR for this repo's README once you are in a usable state. It might help people when looking for more resources/alternatives.

**Comment by marians** [comment]
@tomshaffner Sorry for hijacking the PR and for not reacting before! This seems to have flown below my radar. What's the state? Does it work for you?

**Comment by tomshaffner** [comment]
Honestly it's been so long that I don't remember at this point what the final state was; would have to check the documentation again. Given the retirement of python 2 support in the next month or two though I think any work to convert to python 3 is worth supporting. The changes I made were, I believe, just a lot of the generic ones required to be compatible (e.g. print statement updates, etc.)

**Comment by marians** [comment]
> Given the retirement of python 2 support in the next month or two though I think any work to convert to python 3 is worth supporting. 

Absolutely. I haven't worked with this module in quite a while and don't have any test cases ready. But let's call it "better than what we have" and merge. Thanks very much for the contribution!

**Pull request merged**
